module.exports = function(app) {
  app.constant("VASTAANOTTOTILA", {
    VASTAANOTTANUT_SITOVASTI: "VASTAANOTTANUT_SITOVASTI",
    EI_VASTAANOTETTU_MAARA_AIKANA: "EI_VASTAANOTETTU_MAARA_AIKANA",
    EHDOLLISESTI_VASTAANOTTANUT: "EHDOLLISESTI_VASTAANOTTANUT"
  })
  app.constant("VASTAANOTTO_ACTION", {
    VASTAANOTA_SITOVASTI: "VastaanotaSitovasti",
    VASTAANOTA_EHDOLLISESTI: "VastaanotaEhdollisesti",
    PERU: "Peru"
  })
}