language: scala
jdk:
  - oraclejdk8
services:
  - docker
  - postgresql

addons:
  postgresql: "9.5"

before_cache:
  # This is needed for the maven-dependency-plugin to work to get valinta-tulos-service.war
  - sudo chown -R travis:travis $HOME/.m2

cache:
  directories:
  - $HOME/.m2

before_script:
  - DB_NAME=valintarekisteri
  - psql -c "create database $DB_NAME;" -U postgres
  # Temporary workaround until valinta-tulos-service works regardless of timezone
  - export TZ=Europe/Helsinki

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "Q62deBoXD3jTC9Oy3Jr3OTTBTxFGu3zoARtnEXWskW8oj2c+kN2SGaDEzQ5o6d9Uiia26CHnDIjBrmdy15F5JTxN+nf05FG7p/UxwqPqSPpxJgvHqsZsUodIWWzC3wWLHB5wfGdau43iS4Wn7/TL+r9mX4/g0jIpIm/HvRXWnHQ="
    # AWS_SECRET_ACCESS_KEY
    - secure: "Xzi/wjJDwjm13slAIXjzwXp5j9+dN0dRQxYBG3vYoAP968PkE7QIUf80CsDqCbVM5k2slUN3m6yMLsBY0ggoHHh/gVUgVfRQc3A+cBG54GFbMHgqperng/MDNxArkIFRa8kRwb8UStNrRuw/pmLxMdu+XjUHQppRSPBLLT+tDkQ="
    # PostgreSQL port
    - PGPORT=5432

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - sudo sh -c "printf '\n%s penaali.hard.ware.fi\n' $(dig +short artifactory.opintopolku.fi|head -n1) >> /etc/hosts"
  - nvm use node 6

script:
  - export ARTIFACT_NAME=omatsivut
  - ./cibuild.bash
  - export BASE_IMAGE="base-legacy:0.1"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script:
      ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true
