export const VASTAANOTTOTILA = {
  VASTAANOTTANUT_SITOVASTI: "VASTAANOTTANUT_SITOVASTI",
  EI_VASTAANOTETTU_MAARA_AIKANA: "EI_VASTAANOTETTU_MAARA_AIKANA",
  EHDOLLISESTI_VASTAANOTTANUT: "EHDOLLISESTI_VASTAANOTTANUT"
};

export const VASTAANOTTO_ACTION = {
  VASTAANOTA_SITOVASTI: "VastaanotaSitovasti",
  VASTAANOTA_SITOVASTI_PERU_ALEMMAT: "VastaanotaSitovastiPeruAlemmat",
  VASTAANOTA_EHDOLLISESTI: "VastaanotaEhdollisesti",
  PERU: "Peru"
};

export const urls = {
  "omatsivut.translations": "/omatsivut/translations",
};
