name: Omatsivut

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

permissions:
  id-token: write
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - uses: actions/setup-node@v4
        with:
          node-version: 8

      - name: Set timezone to Europe/Helsinki
        run: |
          sudo timedatectl set-timezone Europe/Helsinki
          echo "Europe/Helsinki" | sudo tee /etc/timezone

      - name: Build PostgreSQL Docker containers
        run: |
          cd postgresql/docker/
          docker build --tag omatsivut-postgres .
          docker build --tag valintarekisteri-postgres .
          cd -

      - name: Build with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./cibuild.bash
      - uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}

  deploy-container:
    needs: test-and-build
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: omatsivut
      base-image: baseimage-fatjar-openjdk17:master
      configfolder: src/main/resources/oph-configuration
      jarfile: omatsivut*SNAPSHOT-allinone
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
